/**
 * In-memory mock data for `@workspace/api-server` Mapazapp routes.
 * Duplicated from `APP/artifacts/mapazapp/src/mock/*` — do not import React/Vite aliases here.
 */
import type {
  AccountPropFirmState,
  AccountRiskGuardState,
  AccountSnapshot,
  AppAccountConfig,
  BacktestParameterSetRow,
  SymbolMapping,
  Zone,
} from "./types";

export const MAPAZAPP_ACTIVE_ACCOUNT_ID = "ACC_THE5ERS_100K_PHASE1_A";

export const MAPAZAPP_MOCK_ACCOUNTS: AppAccountConfig[] = [
  {
    accountId: "ACC_THE5ERS_100K_PHASE1_A",
    displayName: "The5ers 100k — Phase 1 A",
    firmName: "The5ers",
    brokerName: "The5ers MT5",
    accountLogin: "123456",
    accountServer: "The5ers-Server",
    accountSize: 100000,
    currency: "USD",
    challengePhase: "Phase 1",
    status: "active",
    mode: "challenge",
    riskProfileId: "RISK_CONSERVATIVE_05",
    rulesProfileId: "RULES_THE5ERS_HIGH_STAKES",
  },
  {
    accountId: "ACC_PROPXP_50K_PHASE1",
    displayName: "PropXP 50k — Phase 1",
    firmName: "PropXP",
    brokerName: "PropXP MT5",
    accountLogin: "789012",
    accountServer: "PropXP-Server",
    accountSize: 50000,
    currency: "USD",
    challengePhase: "Phase 1",
    status: "watch_only",
    mode: "challenge",
    riskProfileId: "RISK_CONSERVATIVE_025",
    rulesProfileId: "RULES_PROPXP_TWO_PHASE",
  },
  {
    accountId: "ACC_FORWARD_MONITOR_GUARD_BLOCK",
    displayName: "Forward monitor — guard block (mock)",
    firmName: "Mock",
    brokerName: "Mock MT5",
    accountLogin: "900001",
    accountServer: "Mock-Server",
    accountSize: 100000,
    currency: "USD",
    challengePhase: "Phase 1",
    status: "active",
    mode: "demo",
    riskProfileId: "RISK_CONSERVATIVE_05",
    rulesProfileId: "RULES_MOCK",
  },
  {
    accountId: "ACC_FORWARD_MONITOR_REGISTRY_BLOCK",
    displayName: "Forward monitor — registry block (mock)",
    firmName: "Mock",
    brokerName: "Mock MT5",
    accountLogin: "900002",
    accountServer: "Mock-Server",
    accountSize: 100000,
    currency: "USD",
    challengePhase: "Phase 1",
    status: "active",
    mode: "demo",
    riskProfileId: "RISK_CONSERVATIVE_05",
    rulesProfileId: "RULES_MOCK",
  },
  {
    accountId: "ACC_FORWARD_MONITOR_NO_CAND",
    displayName: "Forward monitor — no candidates (mock)",
    firmName: "Mock",
    brokerName: "Mock MT5",
    accountLogin: "900003",
    accountServer: "Mock-Server",
    accountSize: 100000,
    currency: "USD",
    challengePhase: "Phase 1",
    status: "active",
    mode: "demo",
    riskProfileId: "RISK_CONSERVATIVE_05",
    rulesProfileId: "RULES_MOCK",
  },
];

export const MAPAZAPP_MOCK_SNAPSHOTS: Record<string, AccountSnapshot> = {
  ACC_THE5ERS_100K_PHASE1_A: {
    accountId: "ACC_THE5ERS_100K_PHASE1_A",
    displayName: "The5ers 100k — Phase 1 A",
    broker: "The5ers",
    balance: 101245.8,
    equity: 101490.2,
    dailyPnL: 450.4,
    dailyDrawdownPct: 0.31,
    maxDrawdownPct: 1.24,
    openTrades: 1,
    currency: "USD",
    challenge: "Phase 1 - The5ers 100k",
  },
  ACC_PROPXP_50K_PHASE1: {
    accountId: "ACC_PROPXP_50K_PHASE1",
    displayName: "PropXP 50k — Phase 1",
    broker: "PropXP",
    balance: 50120.0,
    equity: 50120.0,
    dailyPnL: 0.0,
    dailyDrawdownPct: 0.0,
    maxDrawdownPct: 0.24,
    openTrades: 0,
    currency: "USD",
    challenge: "Phase 1 - PropXP 50k",
  },
  ACC_FORWARD_MONITOR_GUARD_BLOCK: {
    accountId: "ACC_FORWARD_MONITOR_GUARD_BLOCK",
    displayName: "Forward monitor — guard block (mock)",
    broker: "Mock",
    balance: 100000.0,
    equity: 100000.0,
    dailyPnL: 0.0,
    dailyDrawdownPct: 0.0,
    maxDrawdownPct: 0.0,
    openTrades: 0,
    currency: "USD",
    challenge: "CP16 mock",
  },
  ACC_FORWARD_MONITOR_REGISTRY_BLOCK: {
    accountId: "ACC_FORWARD_MONITOR_REGISTRY_BLOCK",
    displayName: "Forward monitor — registry block (mock)",
    broker: "Mock",
    balance: 100000.0,
    equity: 100000.0,
    dailyPnL: 0.0,
    dailyDrawdownPct: 0.0,
    maxDrawdownPct: 0.0,
    openTrades: 0,
    currency: "USD",
    challenge: "CP16 mock",
  },
  ACC_FORWARD_MONITOR_NO_CAND: {
    accountId: "ACC_FORWARD_MONITOR_NO_CAND",
    displayName: "Forward monitor — no candidates (mock)",
    broker: "Mock",
    balance: 100000.0,
    equity: 100000.0,
    dailyPnL: 0.0,
    dailyDrawdownPct: 0.0,
    maxDrawdownPct: 0.0,
    openTrades: 0,
    currency: "USD",
    challenge: "CP16 mock",
  },
};

export const MAPAZAPP_MOCK_RISK: Record<string, AccountRiskGuardState> = {
  ACC_THE5ERS_100K_PHASE1_A: {
    accountId: "ACC_THE5ERS_100K_PHASE1_A",
    operationalStatus: "TRADING_ALLOWED",
    tradingAllowed: true,
    balance: 101245.8,
    equity: 101490.2,
    dailyStartBalance: 100795.4,
    dailyStartEquity: 100795.4,
    dailyLossLimitAmount: 2015.91,
    dailyLossLimitPercent: 2.0,
    dailyLossUsedAmount: 313.6,
    dailyLossUsedPercent: 0.31,
    dailyLossRemainingAmount: 1702.31,
    dailyLossRemainingPercent: 1.69,
    maxLossLimitAmount: 5000.0,
    maxLossLimitPercent: 5.0,
    maxLossUsedAmount: 1245.8,
    maxLossRemainingAmount: 3754.2,
    riskPerTradePercent: 0.5,
    tradesTakenToday: 1,
    maxTradesPerDay: 3,
    violations: [],
    reason: undefined,
  },
  ACC_FORWARD_MONITOR_GUARD_BLOCK: {
    accountId: "ACC_FORWARD_MONITOR_GUARD_BLOCK",
    operationalStatus: "TRADING_ALLOWED",
    tradingAllowed: true,
    balance: 100000.0,
    equity: 100000.0,
    dailyStartBalance: 100000.0,
    dailyStartEquity: 100000.0,
    dailyLossLimitAmount: 4000.0,
    dailyLossLimitPercent: 4.0,
    dailyLossUsedAmount: 0.0,
    dailyLossUsedPercent: 0.0,
    dailyLossRemainingAmount: 4000.0,
    dailyLossRemainingPercent: 4.0,
    maxLossLimitAmount: 8000.0,
    maxLossLimitPercent: 8.0,
    maxLossUsedAmount: 0.0,
    maxLossRemainingAmount: 8000.0,
    riskPerTradePercent: 0.5,
    tradesTakenToday: 3,
    maxTradesPerDay: 3,
    violations: [],
    reason: "CP16 fixture — max trades reached.",
  },
  ACC_FORWARD_MONITOR_REGISTRY_BLOCK: {
    accountId: "ACC_FORWARD_MONITOR_REGISTRY_BLOCK",
    operationalStatus: "TRADING_ALLOWED",
    tradingAllowed: true,
    balance: 100000.0,
    equity: 100000.0,
    dailyStartBalance: 100000.0,
    dailyStartEquity: 100000.0,
    dailyLossLimitAmount: 4000.0,
    dailyLossLimitPercent: 4.0,
    dailyLossUsedAmount: 0.0,
    dailyLossUsedPercent: 0.0,
    dailyLossRemainingAmount: 4000.0,
    dailyLossRemainingPercent: 4.0,
    maxLossLimitAmount: 8000.0,
    maxLossLimitPercent: 8.0,
    maxLossUsedAmount: 0.0,
    maxLossRemainingAmount: 8000.0,
    riskPerTradePercent: 0.5,
    tradesTakenToday: 0,
    maxTradesPerDay: 5,
    violations: [],
    reason: undefined,
  },
  ACC_FORWARD_MONITOR_NO_CAND: {
    accountId: "ACC_FORWARD_MONITOR_NO_CAND",
    operationalStatus: "TRADING_ALLOWED",
    tradingAllowed: true,
    balance: 100000.0,
    equity: 100000.0,
    dailyStartBalance: 100000.0,
    dailyStartEquity: 100000.0,
    dailyLossLimitAmount: 4000.0,
    dailyLossLimitPercent: 4.0,
    dailyLossUsedAmount: 0.0,
    dailyLossUsedPercent: 0.0,
    dailyLossRemainingAmount: 4000.0,
    dailyLossRemainingPercent: 4.0,
    maxLossLimitAmount: 8000.0,
    maxLossLimitPercent: 8.0,
    maxLossUsedAmount: 0.0,
    maxLossRemainingAmount: 8000.0,
    riskPerTradePercent: 0.5,
    tradesTakenToday: 0,
    maxTradesPerDay: 5,
    violations: [],
    reason: undefined,
  },
  ACC_PROPXP_50K_PHASE1: {
    accountId: "ACC_PROPXP_50K_PHASE1",
    operationalStatus: "WATCH_ONLY",
    tradingAllowed: false,
    balance: 50120.0,
    equity: 50120.0,
    dailyStartBalance: 50120.0,
    dailyStartEquity: 50120.0,
    dailyLossLimitAmount: 2004.8,
    dailyLossLimitPercent: 4.0,
    dailyLossUsedAmount: 0.0,
    dailyLossUsedPercent: 0.0,
    dailyLossRemainingAmount: 2004.8,
    dailyLossRemainingPercent: 4.0,
    maxLossLimitAmount: 4000.0,
    maxLossLimitPercent: 8.0,
    maxLossUsedAmount: 120.0,
    maxLossRemainingAmount: 3880.0,
    riskPerTradePercent: 0.25,
    tradesTakenToday: 0,
    maxTradesPerDay: 2,
    violations: [],
    reason: "Account is in watch_only mode. No trading permitted on this account.",
  },
};

export const MAPAZAPP_MOCK_PROP: Record<string, AccountPropFirmState> = {
  ACC_THE5ERS_100K_PHASE1_A: {
    accountId: "ACC_THE5ERS_100K_PHASE1_A",
    firmName: "The5ers",
    programName: "High Stakes 100k",
    challengePhase: "Phase 1",
    accountSize: 100000,
    profitTargetAmount: 10000,
    profitTargetPercent: 10.0,
    profitAchievedAmount: 1245.8,
    profitAchievedPercent: 1.24,
    dailyDrawdownRule: 5.0,
    maxDrawdownRule: 10.0,
    consistencyEnabled: false,
    bestDayProfit: 868.2,
    totalProfitForPhase: 1245.8,
    consistencyStatus: "COMPLIANT",
    minimumTradingDaysRequired: 0,
    currentTradingDays: 8,
    profitableDaysRequired: 0,
    currentProfitableDays: 6,
    newsTradingAllowed: true,
    blackoutBeforeMinutes: 0,
    blackoutAfterMinutes: 0,
    status: "ON_TRACK",
    warnings: [
      "Avoid trading in the last 15 minutes of the trading day — slippage risk near session close.",
    ],
  },
  ACC_FORWARD_MONITOR_GUARD_BLOCK: {
    accountId: "ACC_FORWARD_MONITOR_GUARD_BLOCK",
    firmName: "Mock",
    programName: "CP16 mock",
    challengePhase: "Phase 1",
    accountSize: 100000,
    profitTargetAmount: 10000,
    profitTargetPercent: 10.0,
    profitAchievedAmount: 0,
    profitAchievedPercent: 0,
    dailyDrawdownRule: 5.0,
    maxDrawdownRule: 10.0,
    consistencyEnabled: false,
    bestDayProfit: 0,
    totalProfitForPhase: 0,
    consistencyStatus: "COMPLIANT",
    minimumTradingDaysRequired: 0,
    currentTradingDays: 0,
    profitableDaysRequired: 0,
    currentProfitableDays: 0,
    newsTradingAllowed: true,
    blackoutBeforeMinutes: 0,
    blackoutAfterMinutes: 0,
    status: "ON_TRACK",
    warnings: [],
  },
  ACC_FORWARD_MONITOR_REGISTRY_BLOCK: {
    accountId: "ACC_FORWARD_MONITOR_REGISTRY_BLOCK",
    firmName: "Mock",
    programName: "CP16 mock",
    challengePhase: "Phase 1",
    accountSize: 100000,
    profitTargetAmount: 10000,
    profitTargetPercent: 10.0,
    profitAchievedAmount: 0,
    profitAchievedPercent: 0,
    dailyDrawdownRule: 5.0,
    maxDrawdownRule: 10.0,
    consistencyEnabled: false,
    bestDayProfit: 0,
    totalProfitForPhase: 0,
    consistencyStatus: "COMPLIANT",
    minimumTradingDaysRequired: 0,
    currentTradingDays: 0,
    profitableDaysRequired: 0,
    currentProfitableDays: 0,
    newsTradingAllowed: true,
    blackoutBeforeMinutes: 0,
    blackoutAfterMinutes: 0,
    status: "ON_TRACK",
    warnings: [],
  },
  ACC_FORWARD_MONITOR_NO_CAND: {
    accountId: "ACC_FORWARD_MONITOR_NO_CAND",
    firmName: "Mock",
    programName: "CP16 mock",
    challengePhase: "Phase 1",
    accountSize: 100000,
    profitTargetAmount: 10000,
    profitTargetPercent: 10.0,
    profitAchievedAmount: 0,
    profitAchievedPercent: 0,
    dailyDrawdownRule: 5.0,
    maxDrawdownRule: 10.0,
    consistencyEnabled: false,
    bestDayProfit: 0,
    totalProfitForPhase: 0,
    consistencyStatus: "COMPLIANT",
    minimumTradingDaysRequired: 0,
    currentTradingDays: 0,
    profitableDaysRequired: 0,
    currentProfitableDays: 0,
    newsTradingAllowed: true,
    blackoutBeforeMinutes: 0,
    blackoutAfterMinutes: 0,
    status: "ON_TRACK",
    warnings: [],
  },
  ACC_PROPXP_50K_PHASE1: {
    accountId: "ACC_PROPXP_50K_PHASE1",
    firmName: "PropXP",
    programName: "Two-Phase 50k",
    challengePhase: "Phase 1",
    accountSize: 50000,
    profitTargetAmount: 4000,
    profitTargetPercent: 8.0,
    profitAchievedAmount: 120.0,
    profitAchievedPercent: 0.24,
    dailyDrawdownRule: 4.0,
    maxDrawdownRule: 8.0,
    consistencyEnabled: true,
    bestDayProfit: 120.0,
    totalProfitForPhase: 120.0,
    consistencyStatus: "COMPLIANT",
    minimumTradingDaysRequired: 5,
    currentTradingDays: 2,
    profitableDaysRequired: 3,
    currentProfitableDays: 1,
    newsTradingAllowed: false,
    blackoutBeforeMinutes: 15,
    blackoutAfterMinutes: 15,
    status: "ON_TRACK",
    warnings: [
      "Consistency rule is enabled. Best day profit must not exceed 50% of total profit.",
      "News trading is blocked — no trades 15 min before or after high-impact events.",
      "Minimum 5 trading days required. Only 2 completed so far.",
    ],
  },
};

export const MAPAZAPP_SYMBOL_MAPPINGS: SymbolMapping[] = [
  {
    canonicalSymbol: "XAUUSD",
    brokerSymbol: "XAUUSD",
    accountId: "ACC_THE5ERS_100K_PHASE1_A",
    brokerId: "the5ers_mt5",
    digits: 2,
    point: 0.01,
    tickSize: 0.01,
    tickValue: 1.0,
    lotStep: 0.01,
  },
  {
    canonicalSymbol: "XAUUSD",
    brokerSymbol: "XAUUSDm",
    accountId: "ACC_PROPXP_50K_PHASE1",
    brokerId: "propxp_mt5",
    digits: 2,
    point: 0.01,
    tickSize: 0.01,
    tickValue: 1.0,
    lotStep: 0.01,
  },
  {
    canonicalSymbol: "EURUSD",
    brokerSymbol: "EURUSD",
    accountId: "ACC_THE5ERS_100K_PHASE1_A",
    brokerId: "the5ers_mt5",
    digits: 5,
    point: 0.00001,
    tickSize: 0.00001,
    tickValue: 1.0,
    lotStep: 0.01,
  },
  {
    canonicalSymbol: "EURUSD",
    brokerSymbol: "EURUSDm",
    accountId: "ACC_PROPXP_50K_PHASE1",
    brokerId: "propxp_mt5",
    digits: 5,
    point: 0.00001,
    tickSize: 0.00001,
    tickValue: 1.0,
    lotStep: 0.01,
  },
];

export const MAPAZAPP_ZONE_SCORING = {
  minScoreForWatching: 40,
  minScoreForConfirmed: 60,
  minScoreForTradeReady: 75,
};

/** Fixed timestamps (stable API) — mirrors `mock/zones.ts` geometry. */
export const MAPAZAPP_MOCK_ZONES: Zone[] = [
  {
    id: "zone_001",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    parameter_set_id: "MZP_IFVG_XAUUSD_V1_SET_003",
    symbol: "XAUUSD",
    direction: "BUY",
    state: "TRADE_READY",
    score: 88,
    ifvgType: "BULLISH_IFVG",
    entryPrice: 2312.5,
    invalidationPrice: 2298.0,
    takeProfitPrice: 2358.0,
    riskRewardRatio: 3.14,
    createdAt: "2026-05-04T08:00:00.000Z",
    updatedAt: "2026-05-04T11:00:00.000Z",
    expiresAt: "2026-05-04T18:00:00.000Z",
    simpleDescription:
      "Gold is near a strong possible buy zone. Conditions look favorable. Wait for price to enter the zone and confirm before trading.",
    notes: "High-confluence IFVG with order block alignment. London session setup.",
  },
  {
    id: "zone_002",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    parameter_set_id: "MZP_IFVG_EURUSD_V1_SET_001",
    symbol: "EURUSD",
    direction: "SELL",
    state: "TRADE_READY",
    score: 76,
    ifvgType: "BEARISH_IFVG",
    entryPrice: 1.0875,
    invalidationPrice: 1.0902,
    takeProfitPrice: 1.0814,
    riskRewardRatio: 2.26,
    createdAt: "2026-05-04T09:00:00.000Z",
    updatedAt: "2026-05-04T11:15:00.000Z",
    expiresAt: "2026-05-04T20:00:00.000Z",
    simpleDescription:
      "EURUSD may be approaching a sell zone. Score is solid. Price has not yet entered the zone — watch and wait.",
    notes: "Bearish IFVG formed during Frankfurt session.",
  },
  {
    id: "zone_003",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    parameter_set_id: "MZP_IFVG_GBPUSD_V1_SET_DRAFT",
    symbol: "GBPUSD",
    direction: "BUY",
    state: "WATCHING",
    score: 61,
    ifvgType: "BULLISH_IFVG",
    entryPrice: 1.268,
    invalidationPrice: 1.264,
    takeProfitPrice: 1.278,
    riskRewardRatio: 2.5,
    createdAt: "2026-05-04T04:00:00.000Z",
    updatedAt: "2026-05-04T10:00:00.000Z",
    expiresAt: "2026-05-04T22:00:00.000Z",
    simpleDescription: "GBPUSD has a possible buy zone forming. Score is moderate — keep watching. No action yet.",
  },
  {
    id: "zone_004",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    parameter_set_id: "MZP_IFVG_NAS100_V1_SET_001",
    symbol: "NAS100",
    direction: "SELL",
    state: "WATCHING",
    score: 55,
    ifvgType: "BEARISH_IFVG",
    entryPrice: 18420.0,
    invalidationPrice: 18560.0,
    takeProfitPrice: 18120.0,
    riskRewardRatio: 2.14,
    createdAt: "2026-05-04T05:00:00.000Z",
    updatedAt: "2026-05-04T10:30:00.000Z",
    simpleDescription: "NAS100 has a possible sell zone, but the score is still low. Not ready for trading yet.",
  },
  {
    id: "zone_005",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    parameter_set_id: "MZP_IFVG_XAUUSD_V1_SET_003",
    symbol: "XAUUSD",
    direction: "SELL",
    state: "CONFIRMED",
    score: 72,
    ifvgType: "BEARISH_IFVG_MITIGATED",
    entryPrice: 2341.0,
    invalidationPrice: 2355.0,
    takeProfitPrice: 2310.0,
    riskRewardRatio: 2.21,
    createdAt: "2026-05-04T03:00:00.000Z",
    updatedAt: "2026-05-04T10:45:00.000Z",
    simpleDescription:
      "Gold sell zone is confirmed. Price is approaching the area. Trade is not ready yet, but conditions are improving.",
  },
  {
    id: "zone_006",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    parameter_set_id: "MZP_IFVG_EURUSD_V1_SET_001",
    symbol: "EURUSD",
    direction: "BUY",
    state: "RETESTING",
    score: 68,
    ifvgType: "BULLISH_IFVG_MITIGATED",
    entryPrice: 1.082,
    invalidationPrice: 1.0805,
    takeProfitPrice: 1.088,
    riskRewardRatio: 4.0,
    createdAt: "2026-05-03T20:00:00.000Z",
    updatedAt: "2026-05-04T10:15:00.000Z",
    simpleDescription:
      "EURUSD is retesting a buy zone that was previously active. Watching to see if it holds.",
  },
  {
    id: "zone_007",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    parameter_set_id: "MZP_IFVG_GBPUSD_V1_SET_DRAFT",
    symbol: "GBPUSD",
    direction: "SELL",
    state: "INVALIDATED",
    score: 0,
    ifvgType: "BEARISH_IFVG",
    entryPrice: 1.272,
    invalidationPrice: 1.274,
    takeProfitPrice: 1.266,
    riskRewardRatio: 3.0,
    createdAt: "2026-05-03T08:00:00.000Z",
    updatedAt: "2026-05-03T20:00:00.000Z",
    simpleDescription:
      "This GBPUSD sell zone was invalidated — price broke through the stop level. Zone is no longer valid.",
  },
  {
    id: "zone_008",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    parameter_set_id: "MZP_IFVG_NAS100_V1_SET_001",
    symbol: "NAS100",
    direction: "BUY",
    state: "EXPIRED",
    score: 0,
    ifvgType: "BULLISH_IFVG",
    entryPrice: 18100.0,
    invalidationPrice: 17950.0,
    takeProfitPrice: 18600.0,
    riskRewardRatio: 3.33,
    createdAt: "2026-05-01T08:00:00.000Z",
    updatedAt: "2026-05-02T08:00:00.000Z",
    expiresAt: "2026-05-02T08:00:00.000Z",
    simpleDescription: "This NAS100 buy zone expired without price reaching the entry level. It is no longer active.",
  },
];

export const MAPAZAPP_MOCK_BACKTESTS: BacktestParameterSetRow[] = [
  {
    id: "MZP_IFVG_XAUUSD_V1_SET_003",
    name: "Alpha v1 — XAUUSD H1 (mock registry row)",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    status: "APPROVED",
    winRate: 58.3,
    profitFactor: 1.82,
    maxDrawdownPct: 4.2,
    totalTrades: 120,
    netProfitPct: 18.4,
    dateRangeFrom: "2023-01-01",
    dateRangeTo: "2024-12-31",
    symbol: "XAUUSD",
    timeframe: "H1",
    allowedAccountIds: ["ACC_THE5ERS_100K_PHASE1_A"],
    approvedAt: "2025-02-15T10:00:00Z",
    trades: [
      {
        id: "bt_001",
        entryTime: "2024-10-01T09:00:00Z",
        exitTime: "2024-10-01T14:00:00Z",
        direction: "BUY",
        entryPrice: 2280.5,
        exitPrice: 2305.2,
        pnlPct: 1.08,
        outcome: "WIN",
      },
    ],
  },
  {
    id: "MZP_IFVG_EURUSD_V1_SET_001",
    name: "EURUSD — alerts-only registry row",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    status: "APPROVED",
    winRate: 61.5,
    profitFactor: 2.14,
    maxDrawdownPct: 3.1,
    totalTrades: 78,
    netProfitPct: 22.1,
    dateRangeFrom: "2024-01-01",
    dateRangeTo: "2024-12-31",
    symbol: "EURUSD",
    timeframe: "H4",
    allowedAccountIds: ["ACC_THE5ERS_100K_PHASE1_A", "ACC_PROPXP_50K_PHASE1"],
    approvedAt: "2025-03-01T14:00:00Z",
  },
  {
    id: "MZP_IFVG_NAS100_V1_SET_001",
    name: "NAS100 — validated (not trade-review approved)",
    strategy_id: "MZP_IFVG_ZONE_REACTION_V1",
    status: "PENDING",
    winRate: 48.0,
    profitFactor: 1.05,
    maxDrawdownPct: 8.0,
    totalTrades: 90,
    netProfitPct: 4.0,
    dateRangeFrom: "2023-06-01",
    dateRangeTo: "2024-12-31",
    symbol: "NAS100",
    timeframe: "M15",
    allowedAccountIds: ["ACC_THE5ERS_100K_PHASE1_A", "ACC_PROPXP_50K_PHASE1"],
  },
];
