/**
 * V1 test-only symbol profiles — NOT broker truth.
 * Duplicated conceptually in IMPLEMENTATION_ASSUMPTIONS.md.
 */
import type { SymbolMarketSpec } from "../src/symbol-profile";

export const TEST_ACCOUNT_ID = "TEST_ACC_V1";

export const V1_TEST_SYMBOL_PROFILES: Record<string, SymbolMarketSpec> = {
  XAUUSD: {
    accountId: TEST_ACCOUNT_ID,
    canonicalSymbol: "XAUUSD",
    brokerSymbol: "XAUUSDm",
    digits: 2,
    point: 0.01,
    tickSize: 0.01,
    tickValue: 1.0,
    contractSize: 100,
    volumeMin: 0.01,
    volumeMax: 50,
    volumeStep: 0.01,
    spreadPoints: 25,
    spreadPrice: 0.25,
  },
  EURUSD: {
    accountId: TEST_ACCOUNT_ID,
    canonicalSymbol: "EURUSD",
    brokerSymbol: "EURUSD",
    digits: 5,
    point: 0.00001,
    tickSize: 0.00001,
    tickValue: 1.0,
    contractSize: 100000,
    volumeMin: 0.01,
    volumeMax: 100,
    volumeStep: 0.01,
    spreadPoints: 12,
    spreadPrice: 0.00012,
  },
  USDJPY: {
    accountId: TEST_ACCOUNT_ID,
    canonicalSymbol: "USDJPY",
    brokerSymbol: "USDJPY",
    digits: 3,
    point: 0.001,
    tickSize: 0.001,
    tickValue: 0.91,
    contractSize: 100000,
    volumeMin: 0.01,
    volumeMax: 100,
    volumeStep: 0.01,
    spreadPoints: 10,
    spreadPrice: 0.01,
  },
  NAS100: {
    accountId: TEST_ACCOUNT_ID,
    canonicalSymbol: "NAS100",
    brokerSymbol: "USTEC",
    digits: 1,
    point: 0.1,
    tickSize: 0.1,
    tickValue: 1.0,
    contractSize: 1,
    volumeMin: 0.1,
    volumeMax: 100,
    volumeStep: 0.1,
    spreadPoints: 15,
    spreadPrice: 1.5,
  },
  BTCUSD: {
    accountId: TEST_ACCOUNT_ID,
    canonicalSymbol: "BTCUSD",
    brokerSymbol: "BTCUSD",
    digits: 1,
    point: 0.1,
    tickSize: 0.1,
    tickValue: 0.01,
    contractSize: 1,
    volumeMin: 0.01,
    volumeMax: 25,
    volumeStep: 0.01,
    spreadPoints: 80,
    spreadPrice: 8.0,
  },
};
